name: Set up
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-1.83.0-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Add wasm32 compilation target
      shell: bash
      run: rustup target add wasm32-unknown-unknown

    - name: Install wasm-pack
      shell: bash
      run: cargo install wasm-pack --version 0.13.1

    - name: Install stylance
      shell: bash
      run: cargo install stylance-cli --version 0.5.2
