name: Set up
inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
  cache-level:
    description: 'How to setup the cache'
    required: true
    type: choice
    options:
      - strict
      - lenient
      - off
runs:
  using: "composite"
  steps:
    - name: Setup cache for Rust compilation
      if: ${{ inputs.cache-level == 'strict' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Setup cache for Rust compilation
      if: ${{ inputs.cache-level == 'lenient' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-${{ github.job }}

    - name: Add wasm32 compilation target
      shell: bash
      run: rustup target add wasm32-unknown-unknown

    - name: Install wasm-pack
      shell: bash
      run: cargo install wasm-pack --version 0.13.1

    - name: Install stylance
      shell: bash
      run: cargo install stylance-cli --version 0.7.0

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ inputs.github-token }}
