name: Set up
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          terrazzo/target/wasm
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.job }}

    - name: Install wasm-pack
      shell: bash
      run: cargo install wasm-pack

    - name: Install stylance
      shell: bash
      run: cargo install stylance-cli
