name: Set up
description: "Set up Rust and WebAssembly toolchain and caching"
inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
  cache-level:
    description: "How to setup the cache"
    required: true
    type: choice
    options:
      - strict
      - lenient
      - off
runs:
  using: "composite"
  steps:
    - name: Get cache week
      if: ${{ inputs.cache-level != 'off' }}
      id: cache-week
      shell: bash
      run: echo "week=$(date +%G-W%V)" >> "$GITHUB_OUTPUT"

    - name: Setup cache for Rust compilation
      if: ${{ inputs.cache-level == 'strict' }}
      uses: actions/cache@v5.0.5
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.bazel/cache/disk/
          ~/.bazel/cache/repository/
          ~/.cache/ms-playwright/
          target/
          terminal/target
        key: ${{ runner.os }}-${{ github.job }}-${{ steps.cache-week.outputs.week }}-${{ hashFiles('**/*.lock') }}

    - name: Restore cache for Rust compilation
      if: ${{ inputs.cache-level == 'lenient' }}
      uses: actions/cache/restore@v5.0.5
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.bazel/cache/disk/
          ~/.bazel/cache/repository/
          ~/.cache/ms-playwright/
          target/
          terminal/target
        key: ${{ runner.os }}-${{ github.job }}-${{ steps.cache-week.outputs.week }}-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.job }}-

    - name: Add wasm32 compilation target
      shell: bash
      run: rustup target add wasm32-unknown-unknown

    - name: Install wasm-pack
      shell: bash
      run: cargo --locked install wasm-pack --version 0.14.0

    - name: Install stylance
      shell: bash
      run: cargo --locked install stylance-cli --version 0.7.4

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ inputs.github-token }}

    - uses: actions/setup-node@v6
    - name: Install Playwright
      shell: bash
      run: npm ci
    - name: Install Chromium
      shell: bash
      run: npx playwright install --with-deps chromium
