#!/bin/bash
cd /Users/richard/Library/Caches/bazel/_bazel_richard/153faf55da8462dddd3bfc25de4644b0/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/bazel/macro_server_update.runfiles/_main && \
  exec env \
    -u JAVA_RUNFILES \
    -u RUNFILES_DIR \
    -u RUNFILES_MANIFEST_FILE \
    -u RUNFILES_MANIFEST_ONLY \
    -u TEST_SRCDIR \
    BUILD_EXECROOT=/Users/richard/Library/Caches/bazel/_bazel_richard/153faf55da8462dddd3bfc25de4644b0/execroot/_main \
    BUILD_ID=ed07a0b8-2048-4a61-b94f-c97edea3bf0d \
    BUILD_WORKING_DIRECTORY=/Users/richard/Documents/GitHub/Terrazzo \
    BUILD_WORKSPACE_DIRECTORY=/Users/richard/Documents/GitHub/Terrazzo \
  /Users/richard/Library/Caches/bazel/_bazel_richard/153faf55da8462dddd3bfc25de4644b0/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/bazel/macro_server_update bazel/macro_server.MODULE.bazel.generated bazel/macro_server.MODULE.bazel true "$@"