[package]
name = "trz-gateway-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = "README.md"
description = { workspace = true }

[lib]

[dependencies]
trz-gateway-common = { workspace = true }

autoclone = { workspace = true }
axum = { workspace = true, features = ["macros", "ws"] }
axum-server = { workspace = true, features = ["tls-rustls"] }
cms = { version = "0.2.3" }
futures = { workspace = true }
nameth = { workspace = true }
oid-registry = { version = "0.8.1" }
openssl = { workspace = true }
rustls-native-certs = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true }
tower-http = { workspace = true, features = ["fs", "trace"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
x509-parser = { workspace = true }

[dev-dependencies]
portpicker = { workspace = true }
reqwest = { workspace = true }
scopeguard = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
