[package]
name = "trz-gateway-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
description = "Secure Proxy / Agents implementation in Rust"
readme = "README.md"
categories = ["network-programming"]
keywords = ["terrazzo", "gateway", "proxy"]

[lib]

[features]
default = []
acme = ["dep:instant-acme", "dep:rcgen"]

[dependencies]
trz-gateway-common = { workspace = true }

autoclone = { workspace = true }
axum = { workspace = true, features = ["macros", "ws"] }
axum-server = { workspace = true, features = ["tls-rustls"] }
bytes = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hyper-util = { workspace = true, features = ["tokio"] }
instant-acme = { workspace = true, optional = true }
nameth = { workspace = true }
openssl = { workspace = true }
pem = { workspace = true }
rcgen = { workspace = true, optional = true }
pin-project = { workspace = true }
prost-types = { workspace = true }
rustls = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["balance", "buffer", "util"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
mime = { workspace = true }
openssl = { workspace = true }
portpicker = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
terrazzo-fixture = { workspace = true }
x509-parser = { workspace = true }

[lints]
workspace = true
