[package]
name = "trz-gateway-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = "README.md"
description = { workspace = true }

[lib]

[dependencies]
trz-gateway-common = { workspace = true }

autoclone = { workspace = true }
axum = { workspace = true, features = ["macros", "ws"] }
axum-server = { workspace = true, features = ["tls-rustls"] }
dashmap = { workspace = true }
futures = { workspace = true }
hyper-util = { workspace = true, features = ["tokio"] }
nameth = { workspace = true }
prost-types = { workspace = true }
rustls = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true, features = ["fs", "trace"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
mime = { workspace = true }
openssl = { workspace = true }
portpicker = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
x509-parser = { workspace = true }
terrazzo-testutils = { workspace = true }

[lints]
workspace = true
