[package]
name = "trz-gateway-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
description = { workspace = true }

[lib]

[dependencies]
axum = { workspace = true }
cms = { workspace = true }
nameth = { workspace = true }
oid-registry = { workspace = true }
openssl = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rustls-native-certs = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
thiserror = { workspace = true }
tokio-rustls = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
x509-parser = { workspace = true }

[dev-dependencies]
scopeguard = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true, features = ["prost"] }

[lints]
workspace = true
