[package]
name = "named-tests"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
named = { workspace = true }

[lib]

[lints]
workspace = true
