pub fn expr_attrs(expr: &syn::Expr) -> &[syn::Attribute] {
    match expr {
        syn::Expr::Array(expr) => &expr.attrs,
        syn::Expr::Assign(expr) => &expr.attrs,
        syn::Expr::Async(expr) => &expr.attrs,
        syn::Expr::Await(expr) => &expr.attrs,
        syn::Expr::Binary(expr) => &expr.attrs,
        syn::Expr::Block(expr) => &expr.attrs,
        syn::Expr::Break(expr) => &expr.attrs,
        syn::Expr::Call(expr) => &expr.attrs,
        syn::Expr::Cast(expr) => &expr.attrs,
        syn::Expr::Closure(expr) => &expr.attrs,
        syn::Expr::Const(expr) => &expr.attrs,
        syn::Expr::Continue(expr) => &expr.attrs,
        syn::Expr::Field(expr) => &expr.attrs,
        syn::Expr::ForLoop(expr) => &expr.attrs,
        syn::Expr::Group(expr) => &expr.attrs,
        syn::Expr::If(expr) => &expr.attrs,
        syn::Expr::Index(expr) => &expr.attrs,
        syn::Expr::Infer(expr) => &expr.attrs,
        syn::Expr::Let(expr) => &expr.attrs,
        syn::Expr::Lit(expr) => &expr.attrs,
        syn::Expr::Loop(expr) => &expr.attrs,
        syn::Expr::Macro(expr) => &expr.attrs,
        syn::Expr::Match(expr) => &expr.attrs,
        syn::Expr::MethodCall(expr) => &expr.attrs,
        syn::Expr::Paren(expr) => &expr.attrs,
        syn::Expr::Path(expr) => &expr.attrs,
        syn::Expr::Range(expr) => &expr.attrs,
        syn::Expr::RawAddr(expr) => &expr.attrs,
        syn::Expr::Reference(expr) => &expr.attrs,
        syn::Expr::Repeat(expr) => &expr.attrs,
        syn::Expr::Return(expr) => &expr.attrs,
        syn::Expr::Struct(expr) => &expr.attrs,
        syn::Expr::Try(expr) => &expr.attrs,
        syn::Expr::TryBlock(expr) => &expr.attrs,
        syn::Expr::Tuple(expr) => &expr.attrs,
        syn::Expr::Unary(expr) => &expr.attrs,
        syn::Expr::Unsafe(expr) => &expr.attrs,
        syn::Expr::While(expr) => &expr.attrs,
        syn::Expr::Yield(expr) => &expr.attrs,
        _ => &[],
    }
}

pub fn take_expr_attrs(expr: &mut syn::Expr) -> Vec<syn::Attribute> {
    let attrs = match expr {
        syn::Expr::Array(expr) => &mut expr.attrs,
        syn::Expr::Assign(expr) => &mut expr.attrs,
        syn::Expr::Async(expr) => &mut expr.attrs,
        syn::Expr::Await(expr) => &mut expr.attrs,
        syn::Expr::Binary(expr) => &mut expr.attrs,
        syn::Expr::Block(expr) => &mut expr.attrs,
        syn::Expr::Break(expr) => &mut expr.attrs,
        syn::Expr::Call(expr) => &mut expr.attrs,
        syn::Expr::Cast(expr) => &mut expr.attrs,
        syn::Expr::Closure(expr) => &mut expr.attrs,
        syn::Expr::Const(expr) => &mut expr.attrs,
        syn::Expr::Continue(expr) => &mut expr.attrs,
        syn::Expr::Field(expr) => &mut expr.attrs,
        syn::Expr::ForLoop(expr) => &mut expr.attrs,
        syn::Expr::Group(expr) => &mut expr.attrs,
        syn::Expr::If(expr) => &mut expr.attrs,
        syn::Expr::Index(expr) => &mut expr.attrs,
        syn::Expr::Infer(expr) => &mut expr.attrs,
        syn::Expr::Let(expr) => &mut expr.attrs,
        syn::Expr::Lit(expr) => &mut expr.attrs,
        syn::Expr::Loop(expr) => &mut expr.attrs,
        syn::Expr::Macro(expr) => &mut expr.attrs,
        syn::Expr::Match(expr) => &mut expr.attrs,
        syn::Expr::MethodCall(expr) => &mut expr.attrs,
        syn::Expr::Paren(expr) => &mut expr.attrs,
        syn::Expr::Path(expr) => &mut expr.attrs,
        syn::Expr::Range(expr) => &mut expr.attrs,
        syn::Expr::RawAddr(expr) => &mut expr.attrs,
        syn::Expr::Reference(expr) => &mut expr.attrs,
        syn::Expr::Repeat(expr) => &mut expr.attrs,
        syn::Expr::Return(expr) => &mut expr.attrs,
        syn::Expr::Struct(expr) => &mut expr.attrs,
        syn::Expr::Try(expr) => &mut expr.attrs,
        syn::Expr::TryBlock(expr) => &mut expr.attrs,
        syn::Expr::Tuple(expr) => &mut expr.attrs,
        syn::Expr::Unary(expr) => &mut expr.attrs,
        syn::Expr::Unsafe(expr) => &mut expr.attrs,
        syn::Expr::While(expr) => &mut expr.attrs,
        syn::Expr::Yield(expr) => &mut expr.attrs,
        _ => return vec![],
    };
    std::mem::take(attrs)
}
