name: Check
runs:
  using: "composite"

  steps:
    - name: Stylance
      run: cd terrazzo && stylance .
      shell: bash

    - name: Clippy
      run: cargo clippy
      shell: bash
    - name: Clippy server debug
      run: cargo clippy --bin terrazzo-server --features server,max_level_debug
      shell: bash
    - name: Clippy server info
      run: cargo clippy --bin terrazzo-server --features server,max_level_info
      shell: bash
    - name: Clippy client debug
      run: cargo clippy --features client,max_level_debug
      shell: bash
    - name: Clippy client info
      run: cargo clippy --features client,max_level_info
      shell: bash

    - name: Rustfmt
      run: cargo fmt
      shell: bash
