name: Check
runs:
  using: "composite"

  steps:
    - name: Stylance web-terminal
      run: cd web-terminal && stylance .
      shell: bash

    - name: Stylance game
      run: cd game && stylance .
      shell: bash

    - name: Clippy
      run: |
        cargo clippy
        cargo clippy --features client,max_level_debug
        cargo clippy --features client,max_level_info
        cargo clippy --bin game --features server,max_level_debug
        cargo clippy --bin game --features server,max_level_info
        cargo clippy --bin web-terminal --features server,max_level_debug
        cargo clippy --bin web-terminal --features server,max_level_info
      shell: bash

    - name: Rustfmt
      run: cargo fmt
      shell: bash
