name: Check
runs:
  using: "composite"

  steps:
    - name: Clippy
      run: |
        cargo clippy --features client
        cargo clippy --features server
        cargo clippy --features=client,server
      shell: bash

    - name: Rustfmt
      run: cargo fmt
      shell: bash
