name: Check
runs:
  using: "composite"

  steps:
    - name: Check
      run: |
        cargo check --features=client,server
        cargo check --features client,debug,diagnostics
        cargo check --features client --release
        cargo check --features server,debug,diagnostics
        cargo check --features server --release
      shell: bash

    - name: Clippy
      run: |
        cargo clippy --features=client,server
        cargo clippy --features client,debug,diagnostics
        cargo clippy --features client --release
        cargo clippy --features server,debug,diagnostics
        cargo clippy --features server --release
      shell: bash

    - name: Rustfmt
      run: cargo fmt
      shell: bash

    - name: Documentation
      run: cargo doc --all-features
      shell: bash
