[package]
name = "terrazzo-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
autoclone-macro = { workspace = true, optional = true }
axum = { workspace = true, optional = true, features = [
    "http1",
    "http2",
    "tracing",
] }
http = { workspace = true, optional = true }
mime = { workspace = true, optional = true }
mime_guess = { workspace = true, optional = true }
named = { workspace = true, optional = true }
scopeguard = { workspace = true, optional = true }
stylance = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
terrazzo-client = { workspace = true, optional = true }
terrazzo-macro = { workspace = true, optional = true }
tracing = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true, features = [
    "DataTransfer",
    "Document",
    "DragEvent",
    "Element",
    "FocusEvent",
    "MouseEvent",
    "Performance",
    "Window",
] }

[build-dependencies]
scopeguard = { workspace = true }
terrazzo-build = { workspace = true }

[features]
default = []
client = [
    "dep:autoclone-macro",
    "dep:named",
    "dep:scopeguard",
    "dep:stylance",
    "dep:terrazzo-client",
    "dep:terrazzo-macro",
    "dep:thiserror",
    "dep:wasm-bindgen",
    "dep:web-sys",
]
server = ["dep:axum", "dep:http", "dep:mime", "dep:mime_guess"]

[package.metadata.stylance]
output_file = "./target/css/common.scss"
folders = ["./src/"]
extensions = [".scss", ".css"]

[lints]
workspace = true
