use std::collections::{BTreeSet, HashMap, HashSet};
use std::fs;
use std::path::PathBuf;

use clap::Parser;
use heck::ToShoutySnakeCase;
use toml::Table;

#[derive(Parser)]
struct Args {
    cargo_toml: PathBuf,
    output_bzl: PathBuf,
}

fn main() -> Result<(), String> {
    let args = Args::parse();
    let manifest = fs::read_to_string(&args.cargo_toml)
        .map_err(|error| format!("failed to read {}: {error}", args.cargo_toml.display()))?;
    let features = parse_features(&manifest)?;
    let output = render_bzl(&features)?;
    fs::write(&args.output_bzl, output)
        .map_err(|error| format!("failed to write {}: {error}", args.output_bzl.display()))?;
    Ok(())
}

fn parse_features(manifest: &str) -> Result<HashMap<String, Vec<String>>, String> {
    let value: Table = manifest
        .parse()
        .map_err(|error| format!("failed to parse Cargo.toml: {error}"))?;
    let Some(features) = value.get("features") else {
        return Ok(HashMap::new());
    };
    let Some(table) = features.as_table() else {
        return Err("[features] must be a TOML table".to_owned());
    };

    let mut result = HashMap::new();
    for (name, value) in table {
        let Some(items) = value.as_array() else {
            return Err(format!("feature {name:?} must be an array"));
        };
        let mut entries = Vec::with_capacity(items.len());
        for item in items {
            let Some(item) = item.as_str() else {
                return Err(format!("feature {name:?} must only contain strings"));
            };
            entries.push(item.to_owned());
        }
        result.insert(name.clone(), entries);
    }
    Ok(result)
}

fn render_bzl(features: &HashMap<String, Vec<String>>) -> Result<String, String> {
    let mut output = String::from("# This file is automatically generated.\n");
    let mut emitted = HashSet::new();

    let mut feature_names = features.keys().cloned().collect::<Vec<_>>();
    feature_names.sort();

    for feature_name in feature_names {
        emit_feature(&mut output, &mut emitted, features, &feature_name)?;
    }

    Ok(output)
}

fn emit_feature(
    output: &mut String,
    emitted: &mut HashSet<String>,
    features: &HashMap<String, Vec<String>>,
    feature_name: &str,
) -> Result<(), String> {
    if emitted.contains(feature_name) {
        return Ok(());
    }

    let entries = features
        .get(feature_name)
        .ok_or_else(|| format!("feature {feature_name:?} is not defined"))?;

    let mut child_features = BTreeSet::new();
    let mut dependencies = BTreeSet::new();

    for entry in entries {
        if let Some(dependency) = entry.strip_prefix("dep:") {
            dependencies.insert(dependency.to_owned());
            continue;
        }
        if entry.contains('/') {
            continue;
        }

        emit_feature(output, emitted, features, entry)?;
        child_features.insert(entry.clone());
    }

    let expression = render_expression(&child_features, &dependencies);
    output.push_str(&format!(
        "{} = {}\n",
        feature_name.to_shouty_snake_case(),
        expression
    ));
    emitted.insert(feature_name.to_owned());

    Ok(())
}

fn render_expression(child_features: &BTreeSet<String>, dependencies: &BTreeSet<String>) -> String {
    let mut parts = child_features
        .iter()
        .map(|feature| feature.to_shouty_snake_case())
        .collect::<Vec<_>>();

    if !dependencies.is_empty() || parts.is_empty() {
        let deps = dependencies
            .iter()
            .map(|dependency| format!("{dependency:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        parts.push(format!("[{deps}]"));
    }

    parts.join(" + ")
}

#[cfg(test)]
mod tests {
    use super::{parse_features, render_bzl};

    #[test]
    fn generates_dependencies_after_children() {
        let features = parse_features(
            r#"
[features]
client = ["dep:stylance"]
terminal = ["client", "dep:scopeguard", "web-sys/Window"]
"#,
        )
        .unwrap();

        let output = render_bzl(&features).unwrap();

        assert_eq!(
            output,
            "\
# This file is automatically generated.\n\
CLIENT = [\"stylance\"]\n\
TERMINAL = CLIENT + [\"scopeguard\"]\n"
        );
    }

    #[test]
    fn generates_empty_lists_for_leaf_features() {
        let features = parse_features(
            r#"
[features]
debug = []
"#,
        )
        .unwrap();

        let output = render_bzl(&features).unwrap();

        assert_eq!(
            output,
            "# This file is automatically generated.\nDEBUG = []\n"
        );
    }

    #[test]
    fn fails_for_unknown_child_features() {
        let features = parse_features(
            r#"
[features]
terminal = ["missing"]
"#,
        )
        .unwrap();

        let error = render_bzl(&features).unwrap_err();

        assert_eq!(error, "feature \"missing\" is not defined");
    }
}
