name: Publish
description: Publishes all crates to crates.io
runs:
  using: "composite"
  steps:
    - name: Login
      run: cargo login $CRATES_TOKEN
      shell: bash
    - name: Publish
      run: |
        cargo publish --locked -p nameth-macro || true
        cargo publish --locked -p nameth || true
        cargo publish --locked -p autoclone || true
        cargo publish --locked -p terrazzo-fixture || true
        cargo publish --locked -p terrazzo-macro || true
        cargo publish --locked -p terrazzo-client || true
        cargo publish --locked -p terrazzo-build || true
        cargo publish --locked -p terrazzo || true
        cargo publish --locked -p trz-gateway-common || true
        cargo publish --locked -p trz-gateway-server || true
        cargo publish --locked -p trz-gateway-client || true
        cargo publish --locked -p terrazzo-pty || true
        cargo publish --locked -p terrazzo-terminal --features prod
      shell: bash
