name: Publish
description: Publishes all crates to crates.io
runs:
  using: "composite"
  steps:
    - name: Login
      run: cargo login $CRATES_TOKEN
      shell: bash
    - name: Publish
      run: |
        cargo publish --locked -p nameth-macro
        cargo publish --locked -p nameth
        cargo publish --locked -p autoclone
        cargo publish --locked -p terrazzo-fixture
        cargo publish --locked -p terrazzo-macro
        cargo publish --locked -p terrazzo-client
        cargo publish --locked -p terrazzo-build
        cargo publish --locked -p terrazzo
        cargo publish --locked -p trz-gateway-common
        cargo publish --locked -p trz-gateway-server
        cargo publish --locked -p trz-gateway-client
        cargo publish --locked -p terrazzo-pty
      shell: bash
