# This file is automatically generated.
BAZEL = []
CLIENT = [
    "@crates//:stylance",
    "@crates//:wasm-bindgen",
    "@crates//:wasm-bindgen-futures",
]
CONVERTER = []
REMOTES_UI = []
CONVERTER_CLIENT = CLIENT + CONVERTER + REMOTES_UI + ["@crates//:web-sys"]
LOGS_PANEL = []
LOGS_PANEL_CLIENT = CLIENT + LOGS_PANEL + ["@crates//:futures"]
PORT_FORWARD = []
PORT_FORWARD_CLIENT = CLIENT + PORT_FORWARD + REMOTES_UI + [
    "@crates//:bitflags",
    "@crates//:scopeguard",
    "@crates//:web-sys",
]
CORRELATION_ID = []
TERMINAL = CORRELATION_ID
TERMINAL_CLIENT = CLIENT + TERMINAL + [
    "@crates//:futures",
    "@crates//:pin-project",
    "@crates//:scopeguard",
    "@crates//:wasm-streams",
    "@crates//:web-sys",
]
TEXT_EDITOR = []
TEXT_EDITOR_CLIENT = CLIENT + REMOTES_UI + TEXT_EDITOR + [
    "@crates//:futures",
    "@crates//:scopeguard",
    "@crates//:serde-wasm-bindgen",
]
CLIENT_ALL = CONVERTER_CLIENT + LOGS_PANEL_CLIENT + PORT_FORWARD_CLIENT + TERMINAL_CLIENT + TEXT_EDITOR_CLIENT
CONCISE_TRACES = []
SERVER = [
    "@crates//:axum-extra",
    "@crates//:base64",
    "@crates//:clap",
    "@crates//:const_format",
    "@crates//:futures",
    "@crates//:humantime",
    "@crates//:inventory",
    "@crates//:jsonwebtoken",
    "@crates//:nix",
    "@crates//:openssl",
    "@crates//:pbkdf2",
    "@crates//:pin-project",
    "@crates//:prost",
    "@crates//:prost-types",
    "@crates//:rpassword",
    "@crates//:scopeguard",
    "@crates//:sha2",
    "@crates//:tokio",
    "@crates//:toml",
    "@crates//:tonic",
    "@crates//:tonic-prost",
    "@crates//:tower",
    "@crates//:tower-http",
    "@crates//:tracing",
    "@crates//:uuid",
]
CONVERTER_SERVER = CONVERTER + SERVER + [
    "@crates//:cms",
    "@crates//:hickory-client",
    "@crates//:oid-registry",
    "@crates//:regex",
    "@crates//:rustls-native-certs",
    "@crates//:serde_yaml_ng",
    "@crates//:simple_asn1",
    "@crates//:tls-parser",
    "@crates//:tokio-rustls",
    "@crates//:unescaper",
    "@crates//:url",
    "@crates//:x509-parser",
]
DEBUG = []
DIAGNOSTICS = []
LOGS_PANEL_SERVER = LOGS_PANEL + SERVER + ["@crates//:tracing-subscriber"]
MAX_LEVEL_DEBUG = []
MAX_LEVEL_INFO = CONCISE_TRACES
NO_WASM_BUILD = []
PORT_FORWARD_SERVER = PORT_FORWARD + SERVER
TERMINAL_SERVER = SERVER + TERMINAL + [
    "@crates//:dashmap",
    "@crates//:pin-project",
    "@crates//:static_assertions",
    "@crates//:tracing-futures",
]
TEXT_EDITOR_SERVER = SERVER + TEXT_EDITOR + [
    "@crates//:libc",
    "@crates//:notify",
    "@crates//:tokio-stream",
]
SERVER_ALL = CONVERTER_SERVER + LOGS_PANEL_SERVER + PORT_FORWARD_SERVER + TERMINAL_SERVER + TEXT_EDITOR_SERVER
PROD = MAX_LEVEL_INFO + SERVER_ALL
RUSTDOC = []
