name: Publish (dry-run)
description: Performs a dry-run publish of all Terrazzo crates to verify they can be published.
runs:
  using: "composite"
  steps:
    - name: Publish (dry-run)
      run: |
        cargo publish --locked -p nameth-macro --dry-run
        cargo publish --locked -p nameth --dry-run
        cargo publish --locked -p autoclone --dry-run
        cargo publish --locked -p terrazzo-fixture --dry-run
        cargo publish --locked -p terrazzo-macro --dry-run
        cargo publish --locked -p terrazzo-client --dry-run
        cargo publish --locked -p terrazzo-build --dry-run
        cargo publish --locked -p terrazzo --dry-run
        cargo publish --locked -p trz-gateway-common --dry-run
        cargo publish --locked -p trz-gateway-server --dry-run
        cargo publish --locked -p trz-gateway-client --dry-run
        cargo publish --locked -p terrazzo-pty --dry-run
        cargo publish --locked -p terrazzo-terminal --dry-run
        cargo publish --locked -p terrazzo-terminal --dry-run --features prod
      shell: bash
