name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'
jobs:
  cargo-build:
    runs-on: ubuntu-latest
    name: Cargo build and test
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up
        uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "strict"

      - name: Build debug
        run: cargo build --locked --bins --features=server,max_level_debug,debug,diagnostics
      - name: Build release
        run: cargo build --locked --bins --features=server,max_level_info --release
        
      - name: Run integration test against debug
        run: ./demo/scripts/integration-test.sh target/debug/demo-server
      - name: Run integration test against release
        run: ./demo/scripts/integration-test.sh target/release/demo-server
  bazel-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    name: Bazel build and test
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up
        uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "strict"

      - name: Bazel build
        run: |
          export PROTOC=$(which protoc)
          bazel build --lockfile_mode=error --action_env=PROTOC //...
      - name: Bazel test
        run: |
          export PROTOC=$(which protoc)
          bazel test --lockfile_mode=error --action_env=PROTOC //...
          
      - name: Buildifier check
        run: bazel run //bazel:buildifier_check
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Publish dry run
        uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "off"
      - uses: ./.github/actions/publish-dry-run
