name: Merge validation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  cargo-build:
    runs-on: ubuntu-latest
    name: Cargo build and test
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Set up
        uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "lenient"

      - name: Build debug
        run: cargo build --bins --features=server,server-all,max_level_debug,debug,diagnostics
      - name: Build release
        run: cargo build --bins --features=server,server-all,max_level_info --release
      - name: Unit tests
        run: RUSTFLAGS="-A unused-crate-dependencies" cargo test --workspace --all-features

      - name: Run integration test against debug
        run: ./demo/scripts/integration-test.sh target/debug/demo-server
      - name: Run integration test against release
        run: ./demo/scripts/integration-test.sh target/release/demo-server

      - name: Install taplo
        run: cargo install taplo-cli --locked
      - name: Format Cargo.toml files
        run: find . -name "Cargo.toml" -exec taplo fmt {} +
      - name: Run Prettier
        run: npx --yes prettier --write "**/*.{yml,yaml}"

      - name: Check for jsdeps changes
        id: jsdeps-changed
        uses: dorny/paths-filter@v4
        with:
          filters: |
            jsdeps:
              - 'terminal/assets/jsdeps/**'
      - name: Update webpack deps
        if: steps.jsdeps-changed.outputs.jsdeps == 'true'
        run: |
          cd terminal/assets/jsdeps
          npm install
          npx webpack

      - name: Commit generated changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: apply Cargo-generated updates"
  bazel-build:
    runs-on: ubuntu-latest
    name: Bazel build and test
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Set up
        uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "lenient"

      - name: Bazel build
        run: |
          export PROTOC=$(which protoc)
          bazel build --action_env=PROTOC //...
      - name: Bazel test
        run: |
          export PROTOC=$(which protoc)
          bazel test --action_env=PROTOC //...
          bazel test --action_env=PROTOC -c opt $(bazel query 'attr("tags", "opt_mode", //...)')

      - name: Update auto-generated files
        run: bazel query 'attr("tags", "auto-generated", //...)' | xargs -r -n1 bazel run

      - name: Buildifier
        run: bazel run //bazel:buildifier

      - name: Commit generated changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: apply Bazel-generated updates"

      - name: Buildifier check
        run: bazel run //bazel:buildifier_check
